profile:
  default: development

project:
  type: website
  render:
    - RESUME.md

website:
  title: "Mit Jayesh Doshi"
  description: "AI Enthusiast & Cybersecurity Professional"
  favicon: "assets/favicon.ico"

  navbar:
    background: dark
    search: false
    left:
      - text: "Home"
        href: "#top"
      - text: "Education"
        href: "#education"
      - text: "Projects"
        href: "#projects"
      - text: "Certifications"
        href: "#certifications"
      - text: "Contact"
        href: "#contact"
    right:
      - icon: github
        href: "https://github.com/mdmit263"
      - icon: linkedin
        href: "https://linkedin.com/in/mitjayeshdoshi"
      - icon: envelope
        href: "mailto:doshimit3015@gmail.com"

  page-footer:
    border: true
    background: dark
    center:
      - text: "<strong>Download PDF</strong>"
        href: "index.pdf"
      - text: "© 2025 Mit Jayesh Doshi — All Rights Reserved"
    right:
      - text: "Back to Top"
        href: "#top"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-location: left
    smooth-scroll: true
    number-sections: false
    css: styles.css
    link-external-newwindow: true
    page-layout: full
  pdf: default

resources:
  - CNAME
